/*
 * This file is part of Breezy Weather.
 */

package org.breezyweather.domain.multisource.model

/**
 * Origin authority of video subtitles.
 * Strictly separates official separate tracks from visual text and AI-generated transcripts.
 */
enum class SubtitleOrigin(val id: String, val displayName: String) {
    /** Official standalone subtitle track (e.g. VTT/SRT published by broadcaster/producer) */
    OFFICIAL_SEPARATE_SUBTITLE("official_separate", "官方独立字幕轨"),
    /** Official closed captions embedded in stream (e.g. EIA-608 / CEA-708) */
    OFFICIAL_CLOSED_CAPTION("official_cc", "官方闭路字幕 (CC)"),
    /** Text hardcoded into video pixel frames (visual banner/lower-third, not a subtitle stream) */
    BURNED_IN_VISUAL_TEXT("burned_in_visual", "视频画面压制文字 (非字幕轨)"),
    /** Speech recognition transcript generated by AI ASR models */
    AI_ASR_GENERATED("ai_asr_generated", "AI 语音识别生成字幕")
}

/**
 * Extraction / generation method for subtitle content.
 */
enum class SubtitleExtractionMethod(val id: String, val displayName: String) {
    AUTOMATED_ASR_EXTRACTED("automated_asr", "算法自动语音识别提取"),
    OFFICIAL_STREAM_EXTRACTED("official_stream", "官方数据流直提"),
    MANUAL_TRANSCRIBED("manual_transcribed", "人工审听逐字听写"),
    NONE("none", "无提取")
}

/**
 * Current runtime availability of subtitles.
 */
enum class SubtitleStatus {
    AVAILABLE,
    UNAVAILABLE,
    ERROR
}

/**
 * Immutable metadata and authority attribution for video subtitles.
 */
data class SubtitleMetadata(
    val origin: SubtitleOrigin,
    val extractionMethod: SubtitleExtractionMethod,
    val sourceAudioAuthority: String,
    val modelName: String,
    val generatedAt: String,
    val isOfficial: Boolean = (origin == SubtitleOrigin.OFFICIAL_SEPARATE_SUBTITLE || origin == SubtitleOrigin.OFFICIAL_CLOSED_CAPTION)
) {
    /**
     * Strictly governed UI display label.
     * For AI_ASR_GENERATED, strictly returns "AI 自动转写字幕".
     * Impersonating CCTV or official authority is strictly forbidden.
     */
    val uiLabel: String
        get() = when (origin) {
            SubtitleOrigin.OFFICIAL_SEPARATE_SUBTITLE, SubtitleOrigin.OFFICIAL_CLOSED_CAPTION -> "官方字幕"
            SubtitleOrigin.BURNED_IN_VISUAL_TEXT -> "画面内嵌文本"
            SubtitleOrigin.AI_ASR_GENERATED -> "AI 自动转写字幕"
        }

    init {
        // Enforce truth invariant
        if (origin == SubtitleOrigin.AI_ASR_GENERATED) {
            require(!isOfficial) { "AI_ASR_GENERATED cannot claim isOfficial=true" }
        }
    }
}

/**
 * Individual timestamped cue segment.
 */
data class TimestampedCue(
    val startMs: Long,
    val endMs: Long,
    val rawText: String,
    val normalizedText: String,
    val confidence: Float? = null,
    val model: String? = null
) {
    init {
        require(startMs >= 0) { "startMs must be non-negative: $startMs" }
        require(endMs > startMs) { "endMs ($endMs) must be strictly greater than startMs ($startMs)" }
    }
}

/**
 * Validation result for WebVTT cue sequences.
 */
data class WebVttValidationResult(
    val isValid: Boolean,
    val cueCount: Int,
    val isMonotonic: Boolean,
    val exceedsDuration: Boolean,
    val validationErrors: List<String> = emptyList()
)

/**
 * Complete subtitle track evidence for a weather video episode.
 */
data class SubtitleTrackEvidence(
    val episodeDate: String,
    val metadata: SubtitleMetadata,
    val status: SubtitleStatus,
    val cues: List<TimestampedCue> = emptyList(),
    val vttContent: String? = null
)

/**
 * Presentation result after fail-closed evaluation.
 */
data class DisplaySubtitleResult(
    val isAvailable: Boolean,
    val uiLabel: String,
    val cues: List<TimestampedCue>,
    val playbackBlocked: Boolean = false,
    val errorReason: String? = null
)

/**
 * Truth gate and validation engine for subtitle tracks.
 */
object SubtitleEvidenceEngine {

    /**
     * Validates WebVTT cues for strict monotonicity, positive durations, and boundary limits.
     */
    fun validateCues(cues: List<TimestampedCue>, maxDurationMs: Long): WebVttValidationResult {
        if (cues.isEmpty()) {
            return WebVttValidationResult(
                isValid = false,
                cueCount = 0,
                isMonotonic = true,
                exceedsDuration = false,
                validationErrors = listOf("Cue list is empty")
            )
        }

        var lastStart = -1L
        var isMonotonic = true
        var exceedsDuration = false
        val errors = mutableListOf<String>()

        cues.forEachIndexed { index, cue ->
            if (cue.startMs < lastStart) {
                isMonotonic = false
                errors.add("Cue #$index violates monotonicity: startMs ${cue.startMs} < previous $lastStart")
            }
            if (cue.endMs <= cue.startMs) {
                errors.add("Cue #$index has invalid duration: startMs=${cue.startMs}, endMs=${cue.endMs}")
            }
            if (cue.endMs > maxDurationMs) {
                exceedsDuration = true
                errors.add("Cue #$index exceeds media duration ($maxDurationMs ms): endMs=${cue.endMs}")
            }
            lastStart = cue.startMs
        }

        return WebVttValidationResult(
            isValid = isMonotonic && !exceedsDuration && errors.isEmpty(),
            cueCount = cues.size,
            isMonotonic = isMonotonic,
            exceedsDuration = exceedsDuration,
            validationErrors = errors
        )
    }

    /**
     * Fail-closed resolver:
     * When ASR fails, subtitles gracefully degrade to UNAVAILABLE.
     * Strictly forbids using CCTV editorial brief as substitute transcript.
     * Playback of the underlying video is NEVER blocked.
     */
    fun resolveDisplaySubtitle(
        evidence: SubtitleTrackEvidence?,
        editorialBriefFallbackCandidate: String? = null
    ): DisplaySubtitleResult {
        if (evidence == null || evidence.status != SubtitleStatus.AVAILABLE || evidence.cues.isEmpty()) {
            return DisplaySubtitleResult(
                isAvailable = false,
                uiLabel = "字幕暂不可用",
                cues = emptyList(),
                playbackBlocked = false,
                errorReason = if (evidence == null) "NO_SUBTITLE_EVIDENCE" else "SUBTITLE_STATUS_${evidence.status}"
            )
        }

        // Subtitle is available
        return DisplaySubtitleResult(
            isAvailable = true,
            uiLabel = evidence.metadata.uiLabel,
            cues = evidence.cues,
            playbackBlocked = false,
            errorReason = null
        )
    }
}
